// Command gen-errors writes docs/ERROR_CODES.md from the registered
// errcode catalogue. Used by `make docs` and CI to keep docs in sync.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	// Side-effect imports populate the global errcode registry.
	_ "github.com/teragrid/forge/internal/cli/cmdaudit"
	_ "github.com/teragrid/forge/internal/cli/cmdbudget"
	_ "github.com/teragrid/forge/internal/cli/cmdclean"
	_ "github.com/teragrid/forge/internal/cli/cmddoctor"
	_ "github.com/teragrid/forge/internal/cli/cmdeval"
	_ "github.com/teragrid/forge/internal/cli/cmdexplain"
	_ "github.com/teragrid/forge/internal/cli/cmdincident"
	_ "github.com/teragrid/forge/internal/cli/cmdlint"
	_ "github.com/teragrid/forge/internal/cli/cmdnew"
	_ "github.com/teragrid/forge/internal/cli/cmdplugin"
	_ "github.com/teragrid/forge/internal/cli/cmdpostmortem"
	_ "github.com/teragrid/forge/internal/cli/cmdscan"
	_ "github.com/teragrid/forge/internal/cli/cmdship"
	_ "github.com/teragrid/forge/internal/cli/cmdstats"
	_ "github.com/teragrid/forge/internal/cli/cmdtelemetry"
	_ "github.com/teragrid/forge/internal/cli/cmdupgrade"
	_ "github.com/teragrid/forge/internal/cli/cmdversion"

	"github.com/teragrid/forge/internal/errcode"
)

func main() {
	out := flag.String("out", "docs/ERROR_CODES.md", "output markdown path")
	check := flag.Bool("check", false, "fail (exit 2) if file is out-of-date")
	flag.Parse()

	body := render()

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			log.Fatalf("read %s: %v", *out, err)
		}
		if string(existing) != body {
			fmt.Fprintln(os.Stderr, "ERROR_CODES.md is out of date — run `make docs`")
			os.Exit(2)
		}
		return
	}

	if err := os.WriteFile(*out, []byte(body), 0o600); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d codes)\n", *out, len(errcode.All()))
}

func render() string {
	var b strings.Builder
	b.WriteString("# forge Error Codes\n\n")
	b.WriteString("Auto-generated by `cmd/gen-errors` — do not edit by hand. ")
	b.WriteString("Run `make docs` to refresh.\n\n")
	b.WriteString("| Code | Description |\n")
	b.WriteString("|------|-------------|\n")
	for _, c := range errcode.All() {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", c.Format(), errcode.Description(c)))
	}
	return b.String()
}
