// Copyright 2024 The Forge Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Command gen-errors writes docs/ERROR_CODES.md from the registered
// errcode catalogue. Used by `make docs` and CI to keep docs in sync.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	// Side-effect imports populate the global errcode registry.
	// Every package that calls errcode.Register must be listed here so that
	// gen-errors captures its codes. Alphabetical within each group.
	//
	// CLI verb packages
	_ "github.com/teragrid/forge/internal/cli/cmdadd"
	_ "github.com/teragrid/forge/internal/cli/cmdadopt"
	_ "github.com/teragrid/forge/internal/cli/cmdagent"
	_ "github.com/teragrid/forge/internal/cli/cmdagents"
	_ "github.com/teragrid/forge/internal/cli/cmdask"
	_ "github.com/teragrid/forge/internal/cli/cmdaudit"
	_ "github.com/teragrid/forge/internal/cli/cmdbackup"
	_ "github.com/teragrid/forge/internal/cli/cmdcheck"
	_ "github.com/teragrid/forge/internal/cli/cmdci"
	_ "github.com/teragrid/forge/internal/cli/cmdclean"
	_ "github.com/teragrid/forge/internal/cli/cmdconfig"
	_ "github.com/teragrid/forge/internal/cli/cmdcontext"
	_ "github.com/teragrid/forge/internal/cli/cmddeploy"
	_ "github.com/teragrid/forge/internal/cli/cmddocs"
	_ "github.com/teragrid/forge/internal/cli/cmddoctor"
	_ "github.com/teragrid/forge/internal/cli/cmdeject"
	_ "github.com/teragrid/forge/internal/cli/cmdeval"
	_ "github.com/teragrid/forge/internal/cli/cmdexplain"
	_ "github.com/teragrid/forge/internal/cli/cmdfix"
	_ "github.com/teragrid/forge/internal/cli/cmdfixtures"
	_ "github.com/teragrid/forge/internal/cli/cmdgenerate"
	_ "github.com/teragrid/forge/internal/cli/cmdhygiene"
	_ "github.com/teragrid/forge/internal/cli/cmdincident"
	_ "github.com/teragrid/forge/internal/cli/cmdinit"
	_ "github.com/teragrid/forge/internal/cli/cmdinsights"
	_ "github.com/teragrid/forge/internal/cli/cmdlearn"
	_ "github.com/teragrid/forge/internal/cli/cmdlint"
	_ "github.com/teragrid/forge/internal/cli/cmdmigrate"
	_ "github.com/teragrid/forge/internal/cli/cmdnew"
	_ "github.com/teragrid/forge/internal/cli/cmdoptimize"
	_ "github.com/teragrid/forge/internal/cli/cmdplugin"
	_ "github.com/teragrid/forge/internal/cli/cmdpostmortem"
	_ "github.com/teragrid/forge/internal/cli/cmdreport"
	_ "github.com/teragrid/forge/internal/cli/cmdreview"
	_ "github.com/teragrid/forge/internal/cli/cmdscan"
	_ "github.com/teragrid/forge/internal/cli/cmdship"
	_ "github.com/teragrid/forge/internal/cli/cmdsla"
	_ "github.com/teragrid/forge/internal/cli/cmdspend"
	_ "github.com/teragrid/forge/internal/cli/cmdtelemetry"
	_ "github.com/teragrid/forge/internal/cli/cmdtest"
	_ "github.com/teragrid/forge/internal/cli/cmdundo"
	_ "github.com/teragrid/forge/internal/cli/cmdupgrade"
	_ "github.com/teragrid/forge/internal/cli/cmdversion"

	"github.com/teragrid/forge/internal/errcode"
)

func main() {
	out := flag.String("out", "docs/ERROR_CODES.md", "output markdown path")
	check := flag.Bool("check", false, "fail (exit 2) if file is out-of-date")
	flag.Parse()

	body := render()

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			log.Fatalf("read %s: %v", *out, err)
		}
		if string(existing) != body {
			fmt.Fprintln(os.Stderr, "ERROR_CODES.md is out of date — run `make docs`")
			os.Exit(2)
		}
		return
	}

	if err := os.WriteFile(*out, []byte(body), 0o600); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d codes)\n", *out, len(errcode.All()))
}

func render() string {
	var b strings.Builder
	b.WriteString("# forge Error Codes\n\n")
	b.WriteString("Auto-generated by `cmd/gen-errors` — do not edit by hand. ")
	b.WriteString("Run `make docs` to refresh.\n\n")
	b.WriteString("| Code | Description |\n")
	b.WriteString("|------|-------------|\n")
	for _, c := range errcode.All() {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", c.Format(), errcode.Description(c)))
	}
	return b.String()
}
