// Copyright 2024 The Forge Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmdship

// Test design for J6 (fix-checkpoint-llm-quality-and-observability):
// checkpoint digests must be computed from the real generated artefact, not
// the one-line checkpoint status message (cp.Detail).
//
// Regression fixture for the exact incident: a real, multi-KB, successful
// arch.md generation previously produced a digest with token_estimate:~19
// and empty decisions/constraints/risks_accepted, because the digest was
// built from cp.Detail ("arch document + openapi.yaml generated by
// anthropic...") instead of the arch.md content itself.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCheckpointArtefactContent_ReadsRealFile — checkpointArtefactContent
// must return the actual arch.md/spec.md/etc. content, not require the
// caller to pass cp.Detail.
func TestCheckpointArtefactContent_ReadsRealFile(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	slug := "my-feature"
	dir := filepath.Join(root, ".forge", "specs", slug)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	realArtefact := "# Architecture: my feature\n\n## Decisions\n- use Postgres\n\n## Constraints\n- p99 < 200ms\n"
	if err := os.WriteFile(filepath.Join(dir, "arch.md"), []byte(realArtefact), 0o600); err != nil {
		t.Fatal(err)
	}

	got := checkpointArtefactContent(root, slug, "Arch")
	if got != realArtefact {
		t.Errorf("checkpointArtefactContent should return arch.md's real content; got: %q", got)
	}
}

// TestCheckpointArtefactContent_UnknownCheckpoint_ReturnsEmpty — checkpoints
// with no essay-style artefact (Ship/Verify) have nothing to read; callers
// must fall back to cp.Detail themselves.
func TestCheckpointArtefactContent_UnknownCheckpoint_ReturnsEmpty(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	if got := checkpointArtefactContent(root, "my-feature", "Ship"); got != "" {
		t.Errorf("expected empty string for a checkpoint with no known artefact file; got: %q", got)
	}
}

// TestMakeDigestFromArtefact_RealContent_NotStatusMessage — the exact J6
// regression: digesting the real artefact must produce non-trivial decisions/
// constraints and a token estimate proportional to real content, not the ~19
// tokens / empty fields a one-line status message would produce.
func TestMakeDigestFromArtefact_RealContent_NotStatusMessage(t *testing.T) {
	t.Parallel()
	statusMessage := "arch document + openapi.yaml generated by anthropic (parallel role debate applied): .forge/specs/my-feature/"
	realArtefact := "# Architecture: my feature\n\n" +
		"## Decisions\n- use Postgres for the ledger table\n- use Redis-free in-process cache\n\n" +
		"## Non-Functional Requirements (Constraints)\n- p99 latency under 200ms\n- no new external dependencies\n\n" +
		"## Risks / Trade-offs\n- single-region deploy accepted for v1\n"

	statusDigest := makeDigestFromArtefact("arch", statusMessage)
	realDigest := makeDigestFromArtefact("arch", realArtefact)

	if len(realDigest.Decisions) == 0 {
		t.Error("digest from real artefact should extract decisions; got none")
	}
	if len(realDigest.Constraints) == 0 {
		t.Error("digest from real artefact should extract constraints; got none")
	}
	if realDigest.TokenEstimate <= statusDigest.TokenEstimate {
		t.Errorf("digest from a multi-line artefact (%d) should estimate more tokens than a one-line status message (%d)",
			realDigest.TokenEstimate, statusDigest.TokenEstimate)
	}
	if len(statusDigest.Decisions) != 0 || len(statusDigest.Constraints) != 0 {
		t.Error("sanity check failed: a bare status message shouldn't itself contain heading-scoped bullets")
	}
	if !strings.Contains(strings.Join(realDigest.Decisions, " "), "Postgres") {
		t.Errorf("expected a decision mentioning Postgres; got: %v", realDigest.Decisions)
	}
}
