// Copyright 2024 The Forge Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package cmdship — G-005: spec.yml manifest.
//
// Every spec directory produced by the Spec checkpoint contains two files:
//
//   - spec.md  — human-readable Markdown specification (prose, GWT criteria)
//   - spec.yml — machine-readable manifest (parsed by Test/Breakdown/Ship
//     checkpoints so they never need to string-grep spec.md)
//
// The schema is documented in docs/spec-schema.md and validated by
// TestSpecManifest_* in spec_manifest_test.go.
package cmdship

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// SpecManifest is the machine-readable counterpart of spec.md.
// It is written as spec.yml in the same directory.
//
// Schema version: 1.
type SpecManifest struct {
	// SchemaVersion allows forward-compatible readers to detect structure changes.
	SchemaVersion int `yaml:"schema_version"`

	// ID is the URL-safe slug derived from the feature description.
	ID string `yaml:"id"`

	// Feature is the original feature description passed to `forge ship`.
	Feature string `yaml:"feature"`

	// Status is the lifecycle stage: "draft" | "active" | "done".
	Status string `yaml:"status"`

	// CreatedAt is the RFC-3339 timestamp when this manifest was first written.
	CreatedAt string `yaml:"created_at,omitempty"`

	// AcceptanceCriteria is a list of Given/When/Then or free-form criteria
	// extracted from the Markdown spec. Each entry is a single sentence.
	AcceptanceCriteria []string `yaml:"acceptance_criteria,omitempty"`

	// ScanPolicy controls which scanner families run at the Ship checkpoint.
	// Defaults to the full set if omitted.
	ScanPolicy SpecScanPolicy `yaml:"scan_policy"`

	// EventsEmitted lists domain events the feature is expected to produce.
	// Populated from lines matching `event:` in spec.md.
	EventsEmitted []string `yaml:"events_emitted,omitempty"`

	// AuthzModel is a free-form note about the authorization model, extracted
	// from lines matching `authz:` in spec.md.
	AuthzModel string `yaml:"authz_model,omitempty"`
}

// SpecScanPolicy controls which scanner families run at the Ship checkpoint.
type SpecScanPolicy struct {
	// Families is the list of scanner family names to run.
	// Allowed values: secrets, sca, sast, license, iac, container, api, supply-chain.
	Families []string `yaml:"families"`
}

// defaultScanFamilies is the full set used when spec.yml has no override.
var defaultScanFamilies = []string{
	"secrets", "sca", "sast", "license",
	"iac", "container", "api", "supply-chain",
}

// newSpecManifest builds a SpecManifest for the given feature and Markdown
// spec content.  The acceptance criteria, events, and authz model are
// extracted from the Markdown text so that downstream checkpoints (Test,
// Breakdown, Ship) can read structured data instead of grepping prose.
func newSpecManifest(slug, feature, specMarkdown string) SpecManifest {
	m := SpecManifest{
		SchemaVersion: 1,
		ID:            slug,
		Feature:       feature,
		Status:        "draft",
		CreatedAt:     time.Now().UTC().Format(time.RFC3339),
		ScanPolicy:    SpecScanPolicy{Families: defaultScanFamilies},
	}
	m.AcceptanceCriteria, m.EventsEmitted, m.AuthzModel = extractSpecFields(specMarkdown)
	return m
}

// MarshalYAML produces the canonical YAML representation with a leading
// comment that warns humans not to edit the file by hand.
func marshalSpecManifest(m SpecManifest) ([]byte, error) {
	raw, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("marshal spec manifest: %w", err)
	}
	header := "# forge spec manifest — auto-generated by `forge ship spec`\n" +
		"# Edit spec.md instead; this file is regenerated on each `forge ship spec` run.\n"
	return append([]byte(header), raw...), nil
}

// writeSpecManifest builds and writes spec.yml next to spec.md.
// Errors are silently swallowed — a missing spec.yml never blocks the ship
// pipeline; it just means downstream checkpoints fall back to spec.md parsing.
func writeSpecManifest(specsDir, slug, feature, specMarkdown string) {
	m := newSpecManifest(slug, feature, specMarkdown)
	data, err := marshalSpecManifest(m)
	if err != nil {
		return
	}
	dir := filepath.Join(specsDir, slug)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	_ = os.WriteFile(filepath.Join(dir, "spec.yml"), data, 0o600)
}

// loadSpecManifest reads and unmarshals spec.yml for the given slug.
// Returns nil if the file does not exist or cannot be parsed.
func loadSpecManifest(specsDir, slug string) *SpecManifest {
	data, err := os.ReadFile(filepath.Join(specsDir, slug, "spec.yml"))
	if err != nil {
		return nil
	}
	var m SpecManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil
	}
	return &m
}

// extractSpecFields parses acceptance criteria, events, and authz model
// from a Markdown spec.  The parser is intentionally simple:
//
//   - Acceptance criteria: lines starting with "- [ ]" or lines in a
//     section whose heading contains "Acceptance Criteria".
//   - Events: lines that start with "event:" (case-insensitive).
//   - AuthzModel: the first line that starts with "authz:" (case-insensitive).
func extractSpecFields(md string) (criteria []string, events []string, authz string) {
	inACSection := false
	sc := bufio.NewScanner(strings.NewReader(md))
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)

		// Detect section headings.
		if strings.HasPrefix(trimmed, "#") {
			lower := strings.ToLower(trimmed)
			inACSection = strings.Contains(lower, "acceptance") && strings.Contains(lower, "criteria")
			continue
		}

		// Acceptance criteria — checkbox items or items in the AC section.
		if strings.HasPrefix(trimmed, "- [ ]") || strings.HasPrefix(trimmed, "- [x]") {
			text := strings.TrimPrefix(strings.TrimPrefix(trimmed, "- [x]"), "- [ ]")
			text = strings.TrimSpace(text)
			if text != "" && text != "<!-- add at least one criterion (Given/When/Then) -->" {
				criteria = append(criteria, text)
			}
			continue
		}
		if inACSection && strings.HasPrefix(trimmed, "-") {
			text := strings.TrimSpace(strings.TrimPrefix(trimmed, "-"))
			if text != "" {
				criteria = append(criteria, text)
			}
			continue
		}

		// Event declarations.
		if lower := strings.ToLower(trimmed); strings.HasPrefix(lower, "event:") {
			val := strings.TrimSpace(trimmed[len("event:"):])
			if val != "" {
				events = append(events, val)
			}
			continue
		}

		// AuthzModel (first match wins).
		if authz == "" {
			if lower := strings.ToLower(trimmed); strings.HasPrefix(lower, "authz:") {
				authz = strings.TrimSpace(trimmed[len("authz:"):])
			}
		}
	}
	return criteria, events, authz
}
