// traceability.go — RFC-005 §6.5 traceability matrix write/read.
// Every AC in the spec is cross-referenced to the tests that cover it,
// along with dimension coverage and a composite score summary.
package cmdship

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// TraceabilityMatrix is the root of the RFC §6.5 traceability.yaml file.
type TraceabilityMatrix struct {
	Feature         string          `yaml:"feature"`
	Generated       string          `yaml:"generated"`    // RFC3339
	SpecVersion     string          `yaml:"spec_version"` // sha256:<hex>
	Matrix          []ACEntry       `yaml:"matrix"`
	CoverageSummary CoverageSummary `yaml:"coverage_summary"`
}

// ACEntry represents a single acceptance criterion and its covering tests.
type ACEntry struct {
	ACID   string      `yaml:"ac_id"`
	ACText string      `yaml:"ac_text"`
	Tests  []TestEntry `yaml:"tests"`
}

// TestEntry represents a single test that covers an AC.
type TestEntry struct {
	ID        string `yaml:"id"`        // e.g. "T-001"
	Name      string `yaml:"name"`      // e.g. "TestInvoiceExport_HappyPath"
	Type      string `yaml:"type"`      // "unit" | "integration" | "fuzz" | "rls"
	Dimension string `yaml:"dimension"` // "D1" | "D2" | ...
	File      string `yaml:"file"`      // workspace-relative path
}

// CoverageSummary is the aggregated coverage metrics written at the bottom of
// traceability.yaml.
type CoverageSummary struct {
	TotalACs          int             `yaml:"total_acs"`
	ACsWithTests      int             `yaml:"acs_with_tests"`
	TotalTests        int             `yaml:"total_tests"`
	DimensionCoverage map[string]bool `yaml:"dimension_coverage"`
	CompositeScore    float64         `yaml:"composite_score"`
	MissingDimensions []string        `yaml:"missing_dimensions"`
	WaivedDimensions  []string        `yaml:"waived_dimensions"`
	GateStatus        string          `yaml:"gate_status"` // "PASS" | "WARNING" | "BLOCK"
}

// WriteTraceability writes m as YAML to <specsDir>/<slug>/traceability.yaml.
// The slug is validated against fssandbox rules: path-traversal slugs are
// rejected before any file I/O. RFC-005 §6.5.
func WriteTraceability(specsDir, slug string, m TraceabilityMatrix) error {
	if err := validateTraceabilitySlug(specsDir, slug); err != nil {
		return err
	}

	outPath := filepath.Join(specsDir, slug, "traceability.yaml")

	// Compute spec_version from spec.md when present.
	specPath := filepath.Join(specsDir, slug, "spec.md")
	if data, err := os.ReadFile(specPath); err == nil {
		hash := sha256.Sum256(data)
		m.SpecVersion = fmt.Sprintf("sha256:%x", hash)
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("traceability marshal: %w", err)
	}
	header := []byte("# auto-generated by forge ship — RFC-005 §6.5\n# Do not edit dimension_coverage or composite_score manually.\n")
	if err := os.WriteFile(outPath, append(header, data...), 0o600); err != nil {
		return fmt.Errorf("traceability write %s: %w", outPath, err)
	}
	return nil
}

// ReadTraceability reads and parses <specsDir>/<slug>/traceability.yaml.
func ReadTraceability(specsDir, slug string) (TraceabilityMatrix, error) {
	if err := validateTraceabilitySlug(specsDir, slug); err != nil {
		return TraceabilityMatrix{}, err
	}

	inPath := filepath.Join(specsDir, slug, "traceability.yaml")
	data, err := os.ReadFile(inPath)
	if err != nil {
		return TraceabilityMatrix{}, fmt.Errorf("traceability read %s: %w", inPath, err)
	}

	// Strip leading comment lines before YAML parse.
	lines := strings.Split(string(data), "\n")
	var yamlLines []string
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		yamlLines = append(yamlLines, line)
	}

	var m TraceabilityMatrix
	if err := yaml.Unmarshal([]byte(strings.Join(yamlLines, "\n")), &m); err != nil {
		return TraceabilityMatrix{}, fmt.Errorf("traceability unmarshal: %w", err)
	}
	return m, nil
}

// validateTraceabilitySlug rejects slugs that would cause path traversal.
// It checks that the resolved path stays within specsDir.
func validateTraceabilitySlug(specsDir, slug string) error {
	if slug == "" {
		return fmt.Errorf("traceability: slug must not be empty")
	}
	// Resolve the target directory and verify it is rooted inside specsDir.
	target := filepath.Clean(filepath.Join(specsDir, slug))
	base := filepath.Clean(specsDir)
	// Ensure target is within base (not equal to base, and has base as prefix).
	rel, err := filepath.Rel(base, target)
	if err != nil {
		return fmt.Errorf("traceability: invalid slug %q: %w", slug, err)
	}
	if strings.HasPrefix(rel, "..") || rel == "." {
		return fmt.Errorf("traceability: slug %q would escape specs directory (path traversal rejected)", slug)
	}
	return nil
}
