// AUTO-GENERATED by forge ship test — G-006 RLS test stubs
// Feature: rearchitect forge framework for llm-first workflows
// Status: RED (intentionally failing)
//
// These tests verify Row-Level Security policies for the feature.
// Run against a local Supabase instance: supabase start

import { describe, it, expect, beforeAll, afterAll } from '@jest/globals';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL ?? 'http://localhost:54321';
const ANON_KEY    = process.env.SUPABASE_ANON_KEY ?? '';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY ?? '';

describe('agent-first-rearchitect — RLS policies', () => {
  const anon    = createClient(SUPABASE_URL, ANON_KEY);
  const service = createClient(SUPABASE_URL, SERVICE_KEY);

  it('anon role cannot read agent-first-rearchitect rows', async () => {
    // TODO: replace table name + assertion after schema migration
    const { data, error } = await anon.from('agent-first-rearchitect').select('*');
    expect(error).not.toBeNull(); // RLS should block anon reads
  });

  it('service role can read all agent-first-rearchitect rows', async () => {
    const { error } = await service.from('agent-first-rearchitect').select('*');
    expect(error).toBeNull();
  });

  it('tenant-A cannot read tenant-B rows', async () => {
    // TODO: implement with two tenant JWT fixtures
    expect(false).toBe(true); // placeholder
  });
});
