// Copyright 2024 The Forge Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package cmdask implements `forge ask` (DEV-M1-47, spec §4).
//
// Answers natural language questions about the current project using the
// Forge LLM bridge and project context snapshot files.
//
// Context is loaded from (in order):
//  1. .forge/context/snapshot.md  (generated by `forge context generate`)
//  2. AGENTS.md
//  3. .forge/manifest (pattern list)
//  4. docs/ARCHITECTURE_OVERVIEW.md  (if present)
//
// Graceful degradation: when no LLM provider is configured, forge ask
// returns a structured "no provider" message with setup instructions
// rather than an error exit.
package cmdask

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/teragrid/forge/internal/errcode"
	"github.com/teragrid/forge/internal/llmprovider"
	"github.com/teragrid/forge/internal/verbmeta"
)

// Reserved error codes (range 4900..4999).
var (
	ErrAskFailed = errcode.Register(errcode.Code(4900), "ask failed")
)

// AskResult is returned by Run and emitted in --json mode.
type AskResult struct {
	Question   string `json:"question"`
	Answer     string `json:"answer"`
	Model      string `json:"model,omitempty"`
	TokensIn   int    `json:"tokens_in,omitempty"`
	TokensOut  int    `json:"tokens_out,omitempty"`
	NoProvider bool   `json:"no_provider,omitempty"`
}

func init() {
	verbmeta.Register(verbmeta.Manifest{
		Verb:    "ask",
		Summary: "Ask a natural language question about the project via the LLM bridge (spec §4).",
		Inputs: []string{
			"<question>  — natural language question about the project",
			"--root <path>",
			"--model <model> — LLM model to use (default: provider default)",
			"--json — emit machine-readable JSON",
		},
		Outputs:      []string{"stdout: LLM answer with context"},
		SideEffects:  []string{"LLM API call; charges may apply"},
		GatesTouched: []string{"§4 ask", "§5 llmbudget"},
		ErrorCodes:   []errcode.Code{ErrAskFailed},
	})
}

// New returns the cobra command for `forge ask`.
func New() *cobra.Command {
	var (
		root   string
		model  string
		asJSON bool
	)
	cmd := &cobra.Command{
		Use:   "ask <question>",
		Short: "Ask a natural language question about the project via the LLM bridge.",
		Long: "forge ask answers natural language questions about the current project.\n\n" +
			"It uses the project context files (AGENTS.md, .forge/manifest, etc.) plus\n" +
			"the configured LLM provider to provide grounded answers.\n\n" +
			"Graceful degradation: when no API key is set, forge ask explains how to\n" +
			"configure a provider rather than exiting with an error.\n\n" +
			"Examples:\n" +
			"  forge ask 'Which migrations are pending?'\n" +
			"  forge ask 'What is the threat model for the auth service?'\n" +
			"  forge ask 'Show me all registered error codes above 2000'",
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			question := strings.Join(args, " ")
			if root == "" {
				cwd, err := os.Getwd()
				if err != nil {
					return errcode.New(ErrAskFailed, "getwd", err)
				}
				root = cwd
			}
			res := Run(root, question, model)
			if asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(res)
			}
			if res.NoProvider {
				fmt.Fprintln(cmd.OutOrStdout(), res.Answer)
				return nil
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Q: %s\n\nA: %s\n", res.Question, res.Answer)
			if res.Model != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "\n[model: %s | in: %d | out: %d tokens]\n",
					res.Model, res.TokensIn, res.TokensOut)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&root, "root", "", "project root (default: cwd)")
	cmd.Flags().StringVar(&model, "model", "", "LLM model to use (default: provider default)")
	cmd.Flags().BoolVar(&asJSON, "json", false, "emit machine-readable JSON")
	return cmd
}

// Run executes the ask request and returns a result. It never returns an error
// so callers get a gracefully degraded response when the LLM is unavailable.
func Run(root, question, model string) AskResult {
	res := AskResult{Question: question}

	// Build context from project files.
	systemCtx := buildContext(root)

	provider, err := llmprovider.Detect()
	if err != nil {
		res.NoProvider = true
		res.Answer = "forge ask: no LLM provider configured.\n\n" +
			"To use forge ask, set one of:\n" +
			"  export ANTHROPIC_API_KEY=<key>   # Anthropic Claude\n" +
			"  export OPENAI_API_KEY=<key>       # OpenAI GPT\n\n" +
			"Then re-run: forge ask " + fmt.Sprintf("%q", question)
		return res
	}

	req := &llmprovider.Request{
		Model:        model,
		SystemPrompt: systemCtx,
		UserPrompt:   question,
		MaxTokens:    1024,
	}

	resp, err := provider.Complete(context.Background(), req)
	if err != nil {
		res.Answer = fmt.Sprintf("forge ask: LLM request failed: %v\n\n"+
			"If this is a transient error, retry with: forge ask %q", err, question)
		return res
	}
	res.Answer = resp.Content
	res.Model = resp.Model
	res.TokensIn = resp.InputTokens
	res.TokensOut = resp.OutputTokens
	return res
}

// buildContext assembles the system prompt from project context files.
func buildContext(root string) string {
	var parts []string
	parts = append(parts, "You are a helpful AI assistant answering questions about a software project. "+
		"Base your answers on the project context below. "+
		"Be concise and accurate. If the answer is not in the context, say so clearly.")

	contextFiles := []struct {
		path  string
		label string
	}{
		{".forge/context/snapshot.md", "Project Context Snapshot"},
		{"AGENTS.md", "AGENTS.md"},
		{"docs/ARCHITECTURE_OVERVIEW.md", "Architecture Overview"},
		{".forge/manifest", "Forge Manifest"},
	}

	for _, cf := range contextFiles {
		data, err := os.ReadFile(filepath.Join(root, cf.path))
		if err != nil {
			continue
		}
		content := strings.TrimSpace(string(data))
		if content == "" {
			continue
		}
		// Truncate very large files to avoid token budget blow-out.
		if len(content) > 8000 {
			content = content[:8000] + "\n\n[...truncated for context window]"
		}
		parts = append(parts, fmt.Sprintf("## %s\n\n%s", cf.label, content))
	}

	return strings.Join(parts, "\n\n---\n\n")
}
