// Copyright 2024 The Forge Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// gen-knowledge-index walks forge-knowledge/knowledge-base/, parses YAML
// frontmatter from each .md file, builds a compact JSON index, then
// gzip-compresses and AES-128-GCM-encrypts it and writes the result as a
// generated Go source file: internal/knowledge/zdata_private.go.
//
// The generated file carries the build tag //go:build kb_private so it is
// excluded from public/open-source builds. Only builds produced internally
// with -tags kb_private embed the real knowledge base.
//
// Usage (run from repo root):
//
//	go run ./cmd/gen-knowledge-index
//	go run ./cmd/gen-knowledge-index --check   # CI gate: exits 2 if stale
//
// Build with knowledge base:
//
//	go build -tags kb_private ./...
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// defaultKey must match internal/knowledge.knowledgeKey exactly.
// Override both via ldflags (runtime) and --key flag (generator) for production.
const defaultKey = "forge-kb-2024-v1"

// indexEntry mirrors knowledge.Entry (no import to keep tool self-contained).
type indexEntry struct {
	ID               string           `json:"id"`
	Category         string           `json:"category"`
	Path             string           `json:"path"`
	Intent           string           `json:"intent"`
	Snippet          string           `json:"snippet"`
	ForgeIntegration forgeIntegration `json:"forge_integration"`
	Tags             []string         `json:"tags"`
}

type forgeIntegration struct {
	ScanFamilies    []string `json:"scan_families"`
	Templates       []string `json:"templates"`
	Conventions     []string `json:"conventions"`
	ShipCheckpoints []string `json:"ship_checkpoints"`
}

type indexFile struct {
	Version string       `json:"version"`
	Entries []indexEntry `json:"entries"`
}

// zdataTemplate is the generated Go file template.
var zdataTemplate = template.Must(template.New("zdata").Parse(`//go:build kb_private

// Code generated by cmd/gen-knowledge-index. DO NOT EDIT.
// This file is NOT committed to the public repository.
// Rebuild with: go run ./cmd/gen-knowledge-index

package knowledge

// encryptedIndex is the gzip-compressed, AES-128-GCM-encrypted knowledge index.
// Decrypt with the key in cipher.go (knowledgeKey / -ldflags override).
// Wire format: nonce(12) || AES-GCM-ciphertext(gzip(JSON))
var encryptedIndex = []byte{
{{.Bytes}}
}
`))

func main() {
	checkMode := flag.Bool("check", false, "verify generated file is up-to-date (exit 2 if stale)")
	kbRoot := flag.String("kb", filepath.Join("forge-knowledge", "knowledge-base"), "path to knowledge-base root")
	outPath := flag.String("out", filepath.Join("internal", "knowledge", "zdata_private.go"), "output Go source path")
	encKey := flag.String("key", defaultKey, "AES-128 encryption key (16 bytes; must match knowledgeKey in cipher.go)")
	jsonOut := flag.String("json-out", "", "optional path to also write plain JSON (for debugging)")
	flag.Parse()

	entries, err := walkKB(*kbRoot)
	if err != nil {
		fatalf("walk: %v", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Category != entries[j].Category {
			return entries[i].Category < entries[j].Category
		}
		return entries[i].ID < entries[j].ID
	})

	idx := indexFile{Version: "1", Entries: entries}
	jsonData, err := json.MarshalIndent(idx, "", "  ")
	if err != nil {
		fatalf("marshal: %v", err)
	}
	jsonData = append(jsonData, '\n')

	if *jsonOut != "" {
		if err := os.WriteFile(*jsonOut, jsonData, 0o600); err != nil {
			fatalf("write json: %v", err)
		}
	}

	encData, err := encryptIndex(jsonData, *encKey)
	if err != nil {
		fatalf("encrypt: %v", err)
	}

	goSrc, err := renderGoFile(encData)
	if err != nil {
		fatalf("render: %v", err)
	}

	if *checkMode {
		existing, readErr := os.ReadFile(*outPath)
		if readErr != nil || !bytes.Equal(existing, goSrc) {
			fmt.Fprintln(os.Stderr, "gen-knowledge-index: zdata_private.go is stale — run: go run ./cmd/gen-knowledge-index")
			os.Exit(2)
		}
		fmt.Printf("gen-knowledge-index: zdata_private.go is up-to-date (%d entries)\n", len(entries))
		return
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o750); err != nil {
		fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(*outPath, goSrc, 0o600); err != nil {
		fatalf("write: %v", err)
	}
	fmt.Printf("gen-knowledge-index: wrote %d entries → %s  (build tag: kb_private)\n", len(entries), *outPath)
}

// ── encryption ────────────────────────────────────────────────────────────────

// encryptIndex gzip-compresses then AES-128-GCM-encrypts jsonData.
// Wire format: nonce(12) || AES-GCM-ciphertext(gzip(JSON))
func encryptIndex(jsonData []byte, keyStr string) ([]byte, error) {
	// gzip compress
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	if _, err := gz.Write(jsonData); err != nil {
		return nil, fmt.Errorf("gzip write: %w", err)
	}
	if err := gz.Close(); err != nil {
		return nil, fmt.Errorf("gzip close: %w", err)
	}
	compressed := buf.Bytes()

	// AES-128-GCM encrypt
	key := padKey(keyStr)
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("gcm: %w", err)
	}
	nonce := make([]byte, gcm.NonceSize()) // 12 bytes
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("nonce: %w", err)
	}
	ciphertext := gcm.Seal(nil, nonce, compressed, nil)
	return append(nonce, ciphertext...), nil
}

func padKey(s string) []byte {
	key := make([]byte, 16)
	copy(key, []byte(s))
	return key
}

// ── Go source rendering ───────────────────────────────────────────────────────

func renderGoFile(data []byte) ([]byte, error) {
	// Format as Go byte slice literal, 16 bytes per line.
	var sb strings.Builder
	for i, b := range data {
		if i > 0 && i%16 == 0 {
			sb.WriteString("\n")
		}
		sb.WriteString(fmt.Sprintf("0x%02x, ", b))
	}
	byteStr := strings.TrimRight(sb.String(), " ")

	var out bytes.Buffer
	if err := zdataTemplate.Execute(&out, struct{ Bytes string }{Bytes: byteStr}); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

// ── KB walker ────────────────────────────────────────────────────────────────

func walkKB(root string) ([]indexEntry, error) {
	var entries []indexEntry
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".md") {
			return nil
		}
		base := filepath.Base(path)
		if base == "README.md" || strings.HasPrefix(base, "_") {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		fm, body, ok := parseFrontmatter(string(data))
		if !ok {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		rel = filepath.ToSlash(rel)

		entry := indexEntry{
			ID:               fm["id"],
			Category:         fm["category"],
			Path:             rel,
			ForgeIntegration: parseForgeIntegration(fm),
			Tags:             parseList(fm["tags"]),
		}
		entry.Intent, entry.Snippet = extractIntentSnippet(body)
		if entry.ID == "" {
			entry.ID = strings.TrimSuffix(base, ".md")
		}
		entries = append(entries, entry)
		return nil
	})
	return entries, err
}

// ── frontmatter parser ────────────────────────────────────────────────────────

func parseFrontmatter(content string) (map[string]string, string, bool) {
	content = strings.TrimPrefix(content, "\xef\xbb\xbf")
	if !strings.HasPrefix(content, "---") {
		return nil, content, false
	}
	rest := content[3:]
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return nil, content, false
	}
	fmRaw := rest[:end]
	body := rest[end+4:]
	if len(body) > 0 && body[0] == '\n' {
		body = body[1:]
	}
	return flattenYAML(fmRaw), body, true
}

func flattenYAML(raw string) map[string]string {
	result := make(map[string]string)
	var parentKey string
	for _, line := range strings.Split(raw, "\n") {
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		indent := len(line) - len(strings.TrimLeft(line, " \t"))
		trimmed := strings.TrimSpace(line)
		if indent == 0 {
			parentKey = ""
		}
		if strings.HasPrefix(trimmed, "- ") && parentKey != "" {
			item := strings.TrimPrefix(trimmed, "- ")
			if result[parentKey] == "" {
				result[parentKey] = "[" + item
			} else {
				result[parentKey] = result[parentKey] + ", " + item
			}
			continue
		}
		idx := strings.Index(trimmed, ":")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:idx])
		val := strings.TrimSpace(trimmed[idx+1:])
		if indent == 0 {
			if val == "" {
				parentKey = key
			} else {
				result[key] = val
			}
		} else if indent >= 2 && parentKey != "" {
			result[parentKey+"."+key] = val
		}
	}
	for k, v := range result {
		if strings.HasPrefix(v, "[") && !strings.HasSuffix(v, "]") {
			result[k] = v + "]"
		}
	}
	return result
}

func parseList(raw string) []string {
	raw = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(raw), "["), "]"))
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func parseForgeIntegration(fm map[string]string) forgeIntegration {
	return forgeIntegration{
		ScanFamilies:    parseList(fm["forge_integration.scan_families"]),
		Templates:       parseList(fm["forge_integration.templates"]),
		Conventions:     parseList(fm["forge_integration.conventions"]),
		ShipCheckpoints: parseList(fm["forge_integration.ship_checkpoints"]),
	}
}

// ── body extraction ───────────────────────────────────────────────────────────

var (
	reIntent   = regexp.MustCompile(`(?m)^>\s+\*\*Intent\*\*:\s*(.+)`)
	reSolution = regexp.MustCompile(`(?ms)^##\s+Solution\s*\n+(.+?)(?:\n##|\z)`)
)

func extractIntentSnippet(body string) (intent, snippet string) {
	if m := reIntent.FindStringSubmatch(body); len(m) > 1 {
		intent = stripMarkdown(strings.TrimSpace(m[1]))
		if len(intent) > 200 {
			intent = intent[:197] + "..."
		}
	}
	sol := ""
	if m := reSolution.FindStringSubmatch(body); len(m) > 1 {
		sol = stripMarkdown(strings.TrimSpace(firstParagraph(m[1])))
	}
	snippet = intent
	if sol != "" && sol != intent {
		comb := intent + " | " + sol
		if len(comb) > 300 {
			comb = comb[:297] + "..."
		}
		snippet = comb
	}
	if len(snippet) > 300 {
		snippet = snippet[:297] + "..."
	}
	return
}

func firstParagraph(s string) string {
	if idx := strings.Index(s, "\n\n"); idx >= 0 {
		return s[:idx]
	}
	return s
}

func stripMarkdown(s string) string {
	s = strings.ReplaceAll(s, "**", "")
	s = strings.ReplaceAll(s, "__", "")
	s = strings.ReplaceAll(s, "*", "")
	s = strings.ReplaceAll(s, "`", "")
	return strings.Join(strings.Fields(s), " ")
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-knowledge-index: "+format+"\n", args...)
	os.Exit(1)
}
