#!/usr/bin/env python3
"""Patch ship.go: G-008 wire writeTaskContextBundles into checkBreakdown,
   G-009 add auto-advance detection in checkCode."""

import sys
import os

SHIP_PATH = os.path.join(os.path.dirname(__file__), '..', 'internal', 'cli', 'cmdship', 'ship.go')

with open(SHIP_PATH, 'rb') as f:
    raw = f.read()

emdash = b'\xc3\xa2\xe2\x82\xac\xe2\x80\x9d'  # mojibake em-dash in this file

# ── G-008: wire writeTaskContextBundles after generateBreakdown succeeds ──────
# Find the line where checkBreakdown returns "ok" after LLM generation.
old_g008 = (
b'\t\t\tif generated != "" {\r\n'
b'\t\t\t\tcp.Status = "ok"\r\n'
b'\t\t\t\tcp.Detail = fmt.Sprintf("breakdown generated by %s: .forge/specs/%s/breakdown.md",\r\n'
b'\t\t\t\t\tpipe.ProviderName(), slug)\r\n'
b'\t\t\t\treturn cp\r\n'
b'\t\t\t}\r\n'
)

new_g008 = (
b'\t\t\tif generated != "" {\r\n'
b'\t\t\t\tcp.Status = "ok"\r\n'
b'\t\t\t\t// G-008: generate per-task context bundles after breakdown.\r\n'
b'\t\t\t\t_ = writeTaskContextBundles(root, slug, 0)\r\n'
b'\t\t\t\tcp.Detail = fmt.Sprintf("breakdown + tasks.md + context bundles generated by %s: .forge/specs/%s/",\r\n'
b'\t\t\t\t\tpipe.ProviderName(), slug)\r\n'
b'\t\t\t\treturn cp\r\n'
b'\t\t\t}\r\n'
)

if old_g008 not in raw:
    print("ERROR: G-008 old fragment not found")
    sys.exit(1)
raw = raw.replace(old_g008, new_g008, 1)
print("G-008 breakdown patch applied")

# ── G-009: auto-advance detection in checkCode ────────────────────────────────
# Find the "Structural fallback (no LLM or no spec/breakdown context)" section.
# We need to add auto-advance detection BEFORE the existing fallback.
old_g009 = (
b'\t// Structural fallback (no LLM or no spec/breakdown context).\r\n'
b'\tif changedFiles > 0 {\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tcp.Detail = fmt.Sprintf("%d modified file(s) detected in working tree", changedFiles)\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\tcp.Status = "warning"\r\n'
b'\tcp.Detail = "no code changes detected in working tree ' + emdash + b' implement tasks then rerun forge ship code"\r\n'
b'\tif pipe == nil {\r\n'
b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to auto-generate a code plan)"\r\n'
b'\t}\r\n'
b'\treturn cp\r\n'
b'}'
)

new_g009 = (
b'\t// G-009: auto-advance — if all tasks.md entries are checked, set AutoAdvance.\r\n'
b'\tif description != "" && allTasksComplete(root, slugify(description)) {\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tcp.AutoAdvance = true\r\n'
b'\t\tcp.Detail = fmt.Sprintf("all tasks complete ' + emdash + b' auto-advancing to Ship checkpoint")\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\r\n'
b'\t// Structural fallback (no LLM or no spec/breakdown context).\r\n'
b'\tif changedFiles > 0 {\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tcp.Detail = fmt.Sprintf("%d modified file(s) detected in working tree", changedFiles)\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\tcp.Status = "warning"\r\n'
b'\tcp.Detail = "no code changes detected in working tree ' + emdash + b' implement tasks then rerun forge ship code"\r\n'
b'\tif pipe == nil {\r\n'
b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to auto-generate a code plan)"\r\n'
b'\t}\r\n'
b'\treturn cp\r\n'
b'}'
)

if old_g009 not in raw:
    print("ERROR: G-009 old fragment not found")
    # print some context
    idx = raw.find(b'Structural fallback')
    print(repr(raw[idx:idx+400]))
    sys.exit(1)
raw = raw.replace(old_g009, new_g009, 1)
print("G-009 auto-advance patch applied")

with open(SHIP_PATH, 'wb') as f:
    f.write(raw)
print("ship.go saved")
