#!/usr/bin/env python3
"""Patch ship.go to add G-006 test artifacts into checkTest."""

import sys
import os

SHIP_PATH = os.path.join(os.path.dirname(__file__), '..', 'internal', 'cli', 'cmdship', 'ship.go')

with open(SHIP_PATH, 'rb') as f:
    raw = f.read()

emdash = b'\xc3\xa2\xe2\x82\xac\xe2\x80\x9d'

old_block = (
b'if len(testFiles) > 0 {\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tcp.Detail = fmt.Sprintf("%d test file(s) found", len(testFiles))\r\n'
b'\t\tif pipe != nil {\r\n'
b'\t\t\tstub, err := generateTestStubs(root, description, pipe)\r\n'
b'\t\t\tif err != nil {\r\n'
b'\t\t\t\tcp.Detail += fmt.Sprintf(" [LLM:%s ' + emdash + b' %s]", pipe.ProviderName(), llmErrNote(err))\r\n'
b'\t\t\t} else if stub != "" {\r\n'
b'\t\t\t\tcp.Detail = fmt.Sprintf("%d test file(s) found; test stubs written by %s to .forge/specs/%s/test-stubs.md",\r\n'
b'\t\t\t\t\tlen(testFiles), pipe.ProviderName(), slugify(description))\r\n'
b'\t\t\t}\r\n'
b'\t\t}\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\t// No test files ' + emdash + b' attempt LLM generation.\r\n'
b'\tif pipe != nil {\r\n'
b'\t\tstub, err := generateTestStubs(root, description, pipe)\r\n'
b'\t\tif err != nil {\r\n'
b'\t\t\tcp.Status = "warning"\r\n'
b'\t\t\tcp.Detail = fmt.Sprintf("no test files found [LLM:%s ' + emdash + b' %s] ' + emdash + b' write failing tests before forge ship code",\r\n'
b'\t\t\t\tpipe.ProviderName(), llmErrNote(err))\r\n'
b'\t\t\treturn cp\r\n'
b'\t\t}\r\n'
b'\t\tif stub != "" {\r\n'
b'\t\t\tcp.Status = "ok"\r\n'
b'\t\t\tcp.Detail = fmt.Sprintf("test stubs generated by %s (see .forge/specs/%s/test-stubs.md) ' + emdash + b' complete before forge ship code",\r\n'
b'\t\t\t\tpipe.ProviderName(), slugify(description))\r\n'
b'\t\t\treturn cp\r\n'
b'\t\t}\r\n'
b'\t}\r\n'
b'\tcp.Status = "warning"\r\n'
b'\tcp.Detail = "no test files found ' + emdash + b' write failing tests before running forge ship code"\r\n'
b'\tif pipe == nil {\r\n'
b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to auto-generate stubs)"\r\n'
b'\t}\r\n'
b'\treturn cp\r\n'
b'}'
)

new_block = (
b'slug := slugify(description)\r\n'
b'\r\n'
b'\t// G-006: write / verify all 4 named test artifacts.\r\n'
b'\tif description != "" {\r\n'
b'\t\tspecMD := ""\r\n'
b'\t\tspecPath := filepath.Join(root, ".forge", "specs", slug, "spec.md")\r\n'
b'\t\tif data, err := os.ReadFile(specPath); err == nil {\r\n'
b'\t\t\tspecMD = string(data)\r\n'
b'\t\t}\r\n'
b'\t\twriteTestArtifacts(root, slug, description, specMD, pipe)\r\n'
b'\t}\r\n'
b'\r\n'
b'\tif len(testFiles) > 0 {\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tmissing := missingTestArtifacts(root, slug)\r\n'
b'\t\tif len(missing) == 0 {\r\n'
b'\t\t\tcp.Detail = fmt.Sprintf("%d test file(s) found; all 4 named artifacts present (tests/%s.*)", len(testFiles), slug)\r\n'
b'\t\t} else {\r\n'
b'\t\t\tcp.Detail = fmt.Sprintf("%d test file(s) found; missing artifacts: %s", len(testFiles), strings.Join(missing, ", "))\r\n'
b'\t\t}\r\n'
b'\t\tif pipe != nil {\r\n'
b'\t\t\tif _, err := generateTestStubs(root, description, pipe); err != nil {\r\n'
b'\t\t\t\tcp.Detail += fmt.Sprintf(" [LLM:%s ' + emdash + b' %s]", pipe.ProviderName(), llmErrNote(err))\r\n'
b'\t\t\t}\r\n'
b'\t\t}\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\t// No test files ' + emdash + b' generate 4 named artifacts.\r\n'
b'\tif pipe != nil {\r\n'
b'\t\tif _, err := generateTestStubs(root, description, pipe); err != nil {\r\n'
b'\t\t\tcp.Status = "warning"\r\n'
b'\t\t\tcp.Detail = fmt.Sprintf("no test files; 4 artifacts written to tests/%s.* [LLM:%s ' + emdash + b' %s]",\r\n'
b'\t\t\t\tslug, pipe.ProviderName(), llmErrNote(err))\r\n'
b'\t\t\treturn cp\r\n'
b'\t\t}\r\n'
b'\t\tcp.Status = "ok"\r\n'
b'\t\tcp.Detail = fmt.Sprintf("4 named test artifacts written to tests/%s.* ' + emdash + b' complete stubs before forge ship code", slug)\r\n'
b'\t\treturn cp\r\n'
b'\t}\r\n'
b'\tcp.Status = "warning"\r\n'
b'\tcp.Detail = fmt.Sprintf("no test files found ' + emdash + b' 4 stub artifacts written to tests/%s.*", slug)\r\n'
b'\tif pipe == nil {\r\n'
b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to generate LLM-assisted stubs)"\r\n'
b'\t}\r\n'
b'\treturn cp\r\n'
b'}'
)

if old_block not in raw:
    print("ERROR: old block not found in ship.go")
    sys.exit(1)

patched = raw.replace(old_block, new_block, 1)
with open(SHIP_PATH, 'wb') as f:
    f.write(patched)
print("G-006 patch applied successfully")
