import sys
raw = open(r'internal\cli\cmdship\ship.go', 'rb').read()
emdash = b'\xc3\xa2\xe2\x82\xac\xe2\x80\x9d'

# G-008 patch
old8 = (b'\t\t\tif generated != "" {\r\n'
        b'\t\t\t\tcp.Status = "ok"\r\n'
        b'\t\t\t\tcp.Detail = fmt.Sprintf("breakdown generated by %s: .forge/specs/%s/breakdown.md",\r\n'
        b'\t\t\t\t\tpipe.ProviderName(), slug)\r\n'
        b'\t\t\t\treturn cp\r\n'
        b'\t\t\t}\r\n')

new8 = (b'\t\t\tif generated != "" {\r\n'
        b'\t\t\t\tcp.Status = "ok"\r\n'
        b'\t\t\t\t// G-008: write per-task context bundles.\r\n'
        b'\t\t\t\t_ = writeTaskContextBundles(root, slug, 0)\r\n'
        b'\t\t\t\tcp.Detail = fmt.Sprintf("breakdown+tasks+bundles by %s: .forge/specs/%s/",\r\n'
        b'\t\t\t\t\tpipe.ProviderName(), slug)\r\n'
        b'\t\t\t\treturn cp\r\n'
        b'\t\t\t}\r\n')

if old8 not in raw:
    print("G-008 not found")
    sys.exit(1)
raw = raw.replace(old8, new8, 1)
print("G-008 applied")

# G-009 patch
old9 = (b'\t// Structural fallback (no LLM or no spec/breakdown context).\r\n'
        b'\tif changedFiles > 0 {\r\n'
        b'\t\tcp.Status = "ok"\r\n'
        b'\t\tcp.Detail = fmt.Sprintf("%d modified file(s) detected in working tree", changedFiles)\r\n'
        b'\t\treturn cp\r\n'
        b'\t}\r\n'
        b'\tcp.Status = "warning"\r\n'
        b'\tcp.Detail = "no code changes detected in working tree ' + emdash + b' implement tasks then rerun forge ship code"\r\n'
        b'\tif pipe == nil {\r\n'
        b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to auto-generate a code plan)"\r\n'
        b'\t}\r\n'
        b'\treturn cp\r\n'
        b'}')

new9 = (b'\t// G-009: auto-advance when all tasks complete.\r\n'
        b'\tif description != "" && allTasksComplete(root, slugify(description)) {\r\n'
        b'\t\tcp.Status = "ok"\r\n'
        b'\t\tcp.AutoAdvance = true\r\n'
        b'\t\tcp.Detail = "all tasks complete ' + emdash + b' auto-advancing to Ship checkpoint"\r\n'
        b'\t\treturn cp\r\n'
        b'\t}\r\n'
        b'\r\n'
        b'\t// Structural fallback (no LLM or no spec/breakdown context).\r\n'
        b'\tif changedFiles > 0 {\r\n'
        b'\t\tcp.Status = "ok"\r\n'
        b'\t\tcp.Detail = fmt.Sprintf("%d modified file(s) detected in working tree", changedFiles)\r\n'
        b'\t\treturn cp\r\n'
        b'\t}\r\n'
        b'\tcp.Status = "warning"\r\n'
        b'\tcp.Detail = "no code changes detected in working tree ' + emdash + b' implement tasks then rerun forge ship code"\r\n'
        b'\tif pipe == nil {\r\n'
        b'\t\tcp.Detail += " (set ANTHROPIC_API_KEY to auto-generate a code plan)"\r\n'
        b'\t}\r\n'
        b'\treturn cp\r\n'
        b'}')

if old9 not in raw:
    print("G-009 not found")
    idx = raw.find(b'Structural fallback')
    print(repr(raw[idx:idx+500]))
    sys.exit(1)
raw = raw.replace(old9, new9, 1)
print("G-009 applied")

open(r'internal\cli\cmdship\ship.go', 'wb').write(raw)
print("Done")
